# Generated by Django 4.0 on 2021-12-26 04:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ComboClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('time', models.DateTimeField(verbose_name='Expires on')),
                ('image', models.ImageField(default='combo', null=True, upload_to='combo')),
                ('numberperson', models.IntegerField()),
                ('percent', models.IntegerField(default=10)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('menu', models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main', 'Main'), ('Dessert', 'Dessert'), ('Vegetarian', 'Vegetarian'), ('Children', 'Children')], default='Sang', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('delive', models.CharField(choices=[('Dang xac nhan', 'Dang xac nhan'), ('Xac nhan', 'Xac nhan'), ('Dang giao', 'Dang giao'), ('Hoan thanh', 'Hoan thanh ')], max_length=30)),
                ('create', models.DateTimeField(default=datetime.datetime(2021, 12, 26, 11, 39, 34, 363787))),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='profiles.cart')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='S', max_length=20)),
                ('soles', models.CharField(choices=[('Mem xop', 'Mem xop'), ('Gion', 'Gion')], default='Gion', max_length=10)),
                ('pecent', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=1)),
                ('comboorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comboorder', to='project.combo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderpizza', to='profiles.order')),
                ('pizaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizaa', to='project.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='ToppingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(choices=[(1, 'Regular'), (2, 'Double'), (3, 'Triple')], default=1)),
                ('orderpiza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_amounts', to='profiles.orderpizza')),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_amount', to='project.topping')),
            ],
        ),
        migrations.CreateModel(
            name='SideDishesInComboClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Noodle', 'Noodle'), ('Drink', 'Drink'), ('GaBBQ', 'GaBBQ'), ('Frenchfries', 'Franchfries'), ('SideDishes', 'Sidedishes')], default='Drink', max_length=15)),
                ('comboclient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sideincomboclient', to='profiles.comboclient')),
                ('sidecomboclient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sidecomboclient', to='project.sidedishes')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pictures')),
                ('name', models.CharField(default='', max_length=100)),
                ('number_phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='Birthday')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaInComboClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comboclient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizzaincomboclient', to='profiles.comboclient')),
                ('pizzacomboclient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizzacomboclient', to='project.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSideDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('pecent', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderside', to='profiles.order')),
                ('sidess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidess', to='project.sidedishes')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('combobox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combobox', to='profiles.comboclient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercombo', to='profiles.order')),
            ],
        ),
    ]