# Generated by Django 3.2.9 on 2021-12-26 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_order_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 13, 24, 29, 499026)),
        ),
    ]
