# Generated by Django 3.2.9 on 2022-01-11 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('profiles', '0004_auto_20211230_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpizza',
            name='rating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='topping',
            field=models.CharField(choices=[('Thêm phomai phủ', 'Thêm phomai phủ'), ('Thêm phomai viền', 'Thêm phomai viền'), ('Double sốt', 'Double sốt')], default='Thêm phomai phủ', max_length=30),
        ),
        migrations.AddField(
            model_name='ordersidedishes',
            name='comboorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comboside', to='project.combo'),
        ),
        migrations.AddField(
            model_name='ordersidedishes',
            name='rating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 15, 21, 36, 625524)),
        ),
    ]
