# Generated by Django 3.2.9 on 2022-01-11 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220111_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 15, 50, 12, 772080)),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='topping',
            field=models.CharField(blank=True, choices=[('Thêm phomai phủ', 'Thêm phomai phủ'), ('Thêm phomai viền', 'Thêm phomai viền'), ('Double sốt', 'Double sốt')], max_length=30, null=True),
        ),
    ]
