# Generated by Django 3.2.9 on 2022-01-11 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20220111_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 15, 55, 37, 363298)),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='topping',
            field=models.CharField(blank=True, choices=[('Thêm phô mai phủ', 'Thêm phô mai phủ'), ('Thêm phô mai viền', 'Thêm phô mai viền'), ('Double sốt', 'Double sốt')], max_length=30, null=True),
        ),
    ]
