# Generated by Django 3.2.9 on 2022-01-12 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20220112_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 11, 24, 17, 590646)),
        ),
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
