# Generated by Django 3.2.9 on 2022-01-14 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20220112_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 15, 38, 16, 328373)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delive',
            field=models.CharField(choices=[('Dang xac nhan', 'Dang xac nhan'), ('Xac nhan', 'Xac nhan'), ('Dang giao', 'Dang giao'), ('Hoan thanh', 'Hoan thanh '), ('Huy', 'Huy')], max_length=30),
        ),
    ]
