# Generated by Django 4.0 on 2021-12-26 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(verbose_name='Expires on')),
                ('image', models.ImageField(default='combo', upload_to='combo')),
                ('numberperson', models.IntegerField()),
                ('percent', models.IntegerField(default=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('menu', models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main', 'Main'), ('Dessert', 'Dessert'), ('Vegetarian', 'Vegetarian'), ('Children', 'Children')], default='Sang', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('costm', models.IntegerField()),
                ('costl', models.IntegerField()),
                ('image', models.ImageField(default='defaultpizza.webp', upload_to='pizza')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('menu', models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main', 'Main'), ('Dessert', 'Dessert'), ('Vegetarian', 'Vegetarian'), ('Children', 'Children')], default='Appetizer', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SideDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('image', models.ImageField(default='defaultdishes.jpg', upload_to='sidedishes')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('menu', models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main', 'Main'), ('Dessert', 'Dessert'), ('Vegetarian', 'Vegetarian'), ('Children', 'Children')], default='Sang', max_length=10)),
                ('type', models.CharField(choices=[('Noodle', 'Noodle'), ('Drink', 'Drink'), ('GaBBQ', 'GaBBQ'), ('Frenchfries', 'Franchfries'), ('SideDishes', 'Sidedishes')], default='SideDishes', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='topping.jpg', upload_to='topping')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SideDishesInCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Noodle', 'Noodle'), ('Drink', 'Drink'), ('GaBBQ', 'GaBBQ'), ('Frenchfries', 'Franchfries'), ('SideDishes', 'Sidedishes')], default='Drink', max_length=15)),
                ('combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sideincombo', to='project.combo')),
                ('sidecombo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sidecombo', to='project.sidedishes')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidescore', to='project.sidedishes')),
            ],
        ),
        migrations.CreateModel(
            name='ScorePizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzascore', to='project.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comboscore', to='project.combo')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaInCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizzaincombo', to='project.combo')),
                ('pizzacombo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizzacombo', to='project.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='pizzas',
            field=models.ManyToManyField(related_name='pizzas', to='project.Pizza'),
        ),
    ]
